### ISSUE TITLE
Add NWB export pytests for Open Ephys data

### ISSUE THREAD

**Issue by kabilar** [datajoint/workflow-array-ephys#52]
- The current pytests use subject5 which is SpikeGLX data.
- The current pytests are comprehensive and there are minimal differences between SpikeGLX and Open Ephys data once in the DataJoint Elements tables, but it would be good to also add pytests for Open Ephys data for when loading from source files.

**Comment by CBroz1** [comment]
Duplicate of #60, which also links to discussion
