### ISSUE TITLE
cannot import name 'ephys_report' from 'element_array_ephys' 

### ISSUE THREAD

**Issue by vncntprvst** [datajoint/workflow-array-ephys#85]
### Description
In example notebook `02-workflow-structure-optional` the call `from workflow_array_ephys.pipeline import lab, subject, session, probe, ephys` results in this error: 
```
ImportError: cannot import name 'ephys_report' from 'element_array_ephys' (C:\Users\wanglab\miniconda3\envs\workflow-array-ephys\lib\site-packages\element_array_ephys\__init__.py)
```

### Reproducibility
Include:
- Windows 10 Pro Version 10.0.19044 Build 19044
- [workflow-array-ephys](https://github.com/datajoint/workflow-array-ephys) Commit 6754449
- MySQL 5.7
- MySQL Deployment Strategy local docker mysql-docker (datajoint/mysql)
- Minimum number of steps to reliably reproduce the issue: install workflow
- Complete error stack as a result of evaluating the above steps
```
ImportError                               Traceback (most recent call last)
Cell In[2], line 2
      1 import datajoint as dj
----> 2 from workflow_array_ephys.pipeline import lab, subject, session, probe, ephys

File C:\Code\Datajoint\workflow-array-ephys\workflow_array_ephys\pipeline.py:7
      5 from element_session import session_with_datetime as session
      6 from element_event import trial, event
----> 7 from element_array_ephys import probe, ephys_report
      9 from element_animal.subject import Subject
     10 from element_lab.lab import Source, Lab, Protocol, User, Project
```

### Expected Behavior
`from element_array_ephys import probe, ephys_report` should work.

### Additional Research and Context
By default the workflow installs `element-array-ephys` from the `run_kilosort` branch (see [requirements `element-array-ephys @ git+https://github.com/datajoint/element-array-ephys@run_kilosort`](https://github.com/datajoint/workflow-array-ephys/blob/67544497047e3e7d4fc4441dd16e2b781a985840/requirements.txt#L2)). That branch does not yet have the 2022-10-28 update's new schema `ephys_report`, which is used in the workflow's pipeline (See [`workflow_array_ephys\pipeline.py:7`---->`from element_array_ephys import probe, ephys_report`](https://github.com/datajoint/workflow-array-ephys/blob/67544497047e3e7d4fc4441dd16e2b781a985840/workflow_array_ephys/pipeline.py#L7)). 

I can just edit the requirements or install directly `element-array-ephys` from the main branch. Unless you have other suggestions? 
Thanks

**Comment by CBroz1** [comment]
Thanks for letting us know @vncntprvst! We've been doing some work on main, but haven't pushed the same updates to the `run_kilosort` branch. I'll see if we can tackle this this week.

**Comment by vncntprvst** [comment]
Thanks everyone!
